# This file describes an application. You can have multiple applications
# in the same project.


# The name of this app. Must be unique within a project.
name: php

# The toolstack used to build the application.
toolstack: "php:symfony"

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: "mysql:mysql"

# The configuration of app when it is exposed to the web.
web:
    # The public directory of the app, relative to its root.
    document_root: "/"
    # The front-controller script to send non-static requests to.
    passthru: "/index.php"

# The size of the persistent disk of the application (in MB).
disk: 2048

# The mounts that will be performed when the package is deployed.
mounts:
    "/public/var": "shared:files/var"
    "/public/app/etc": "shared:files/etc"
    "/public/media": "shared:files/media"

# The hooks executed at various points in the lifecycle of the application.
# note that the .platform-read-write-dirs contains the directories that need to be R/W
hooks:
    # We run build hooks before your application has been packaged.
    build: |
        cd public
        ./magento-build.sh
    # We run deploy hook after your application has been deployed and started.
    deploy: |
        cd /app/public
        ./magento-deploy.sh