# The name of this app. Must be unique within a project.
name: "php"
type: php
build:
    # The default build flavor is composer
    flavor: composer
web:
  document_root: "/"
  passthru: "/index.php"
# Here we say we want access to a mysql instance we call "database" this one is configured in .platform/services.yaml
relationships:
    database: "mysql:mysql"
disk: 2048