"http://{default}/":
    type: upstream
    upstream: "drupal:php"

"http://www.{default}/":
    type: redirect
    to: "http://{default}/"

"http://symfony.{default}/":
    type: upstream
    upstream: "symfony:php"
